- added recursive snapshot command line switch - fixed --no-repl logic - on target changed to 'gzip -dc' from 'zcat' since on some systems zcat != gzcat    note: you will need to re-run target-config to update config - add pre-run check for commands to confirm options & config are supported

diff --git a/zfs-repl b/zfs-repl
--- a/zfs-repl
+++ b/zfs-repl
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Date: 2013-02-05
-# Version: 2.5.3
+# Version: 2.5.4
 #
 # Credits: 
 #    Mike La Spina for the original concept and script http://blog.laspina.ca/
@@ -15,6 +15,13 @@
 #    Maintains a runing snapshot archive for X time
 #
 # Enhancements/Fixes:
+#  2014.02.16
+#  By slefevre
+#   - added recursive snapshot command line switch
+#   - fix --no-repl logic
+#   - on target changed to 'gzip -dc' from 'zcat' since on some systems zcat != gzcat
+#      note: you will need to re-run target-config to update config 
+#   - add pre-run check for commands to confirm options & config are supported
 #  2014.02.12
 #   By slefevre
 #   - Bug fixes
@@ -70,29 +77,29 @@ mail_to=
 mail_subject=
 
 #local bins
-ZFS=zfs
-GZIP=gzip
-NC=nc
-SOCAT=socat
-LOGGER=logger
-MBUFFER=mbuffer
-XZ=xz
-DATE=date
-MAILX=mailx
-CAT=cat
-PV=pv
-SHUF=shuf
-OPENSSL=openssl
+ZFS=
+GZIP=
+NC=
+SOCAT=
+LOGGER=
+MBUFFER=
+XZ=
+DATE=
+MAILX=
+CAT=
+PV=
+SHUF=
+OPENSSL=
 
 #target host bins
-RMT_ZFS=zfs
-RMT_ZCAT=zcat
-RMT_NC=nc
-RMT_SOCAT=socat
-RMT_MBUFFER=mbuffer
-RMT_XZCAT=xzcat
-RMT_CAT=cat
-RMT_OPENSSL=openssl
+RMT_ZFS=
+RMT_GZIP=
+RMT_NC=
+RMT_SOCAT=
+RMT_MBUFFER=
+RMT_XZCAT=
+RMT_CAT=
+RMT_OPENSSL=
 
 # settings
 SSH_CIPHER=
@@ -131,6 +138,7 @@ VERBOSE=
 CLEAN=false
 COMPARE=false
 SNAPSHOT=true
+RECURSIVE_SNAP=
 REPLICATE=true
 SENDMAIL=false
 ERR_MAIL=false
@@ -203,6 +211,7 @@ usage() {
 	echo "                     e.g. \"7 days ago\", \"12 hours ago\" (default infinite)"
 	echo "  -T --dest-snap-retain max time to preserve snapshots on target"
 	echo "                     (see -t option for examples)"
+	echo "  -R --recurse      recursively  create  snapshots  of all descendent datasets"
 	echo "  -v --verbose      verbose"
 	echo "  -c --clean-snaps  clean snapshots in target that are not in source"
 	echo "  -k --compare      compare source and target with checksum using rsync"
@@ -236,6 +245,108 @@ usage() {
 	echo "  -h --help         display usage options "
 	exit 
 }
+
+#######################################################################################
+#
+# Function check source/target commands
+#
+check_cmd() {
+	# params
+	# source/target test
+	# exec var_name
+	# exec name
+	# option message
+	local sys
+	local var_name
+	local exec_name
+	local opt_msg
+	[ $# -lt 3 ] && exit 1
+	sys=$1
+	shift
+	var_name=$1
+	shift
+	exec_name=$1
+	shift
+	opt_msg="$*"
+	
+	case $sys in
+		source)
+			[ ! -x "${!var_name}" ] && log_error "-> ERROR: ${exec_name} not defined, not found, or not executable on source system.  Check ${var_name}= value in /etc/$(basename $0 .sh)/$(basename $0 .sh).conf. \'$opt_msg\' isn't available with current configuration!"
+			;;
+		target)
+			[ -z "${!var_name}" ] && log_error "-> ERROR: ${exec_name} is not defined for target system. Check ${var_name}= value in /etc/$(basename $0 .sh)/${TGT_HOST}.conf. '$opt_msg' isn't available with current configuration!"
+			;;
+	esac
+#	echo "${!var_name} OK!"
+}
+
+#######################################################################################
+#
+# Function check setting before launching anything
+#
+launch_check() {
+	local option
+
+	PROTOCOL=${PROTOCOL^^}
+	case $PROTOCOL in
+		NETCAT)
+			option="-o|--protocol NETCAT"
+			check_cmd "source" "NC" "nc (netcat)" "$option"
+			check_cmd "target" "RMT_NC" "nc (netcat)" "$option"
+			;;
+		SOCAT)
+			option="-o|--protocol SOCAT"
+			check_cmd "source" "SOCAT" "socat" "$option"
+			check_cmd "target" "RMT_SOCAT" "socat" "$option"
+			;;
+		NETSOCAT)
+			option="-o|--protocol NETSOCAT"
+			check_cmd "source" "SOCAT" "socat" "$option"
+			check_cmd "target" "RMT_NC" "nc (netcat)" "$option"
+			;;
+		MBUFFER)
+			option="-o|--protocol MBUFFER"
+			check_cmd "source" "MBUFFER" "mbuffer" "$option"
+			check_cmd "target" "RMT_MBUFFER" "mbuffer" "$option"
+			;;
+	esac
+
+	COMPRESSION=${COMPRESSION^^}
+	case $COMPRESSION in
+		GZIP)
+			option="-C|--compression GZIP"
+			check_cmd "source" "GZIP" "gzip" "$option"
+			check_cmd "target" "RMT_GZIP" "gzip" "$option"
+			;;
+		XZ)
+			option="-C|--compression XZ"
+			check_cmd "source" "XZ" "xz" "$option"
+			check_cmd "target" "RMT_XZCAT" "xzcat" "$option"
+			;;
+	esac
+
+	if [ $ENCRYPT == true ]; then
+		option="-e|--encrypt"
+		check_cmd "source" "OPENSSL" "openssl" "$option"
+		check_cmd "target" "RMT_OPENSSL" "openssl" "$option"
+	fi
+
+	if [ $STATS == true ]; then
+		check_cmd "source" "PV" "pv (pipeview)" "-S|--stats"
+	fi
+	
+	if [[ $SENDMAIL == true || $ERR_MAIL == true ]]; then
+		check_cmd "source" "MAILX" "mailx" "-m|--email-errors|-M|--email"
+	fi
+	if [[ "$MAX_TIME" != "" || "$RMT_MAX_TIME" != "" ]]; then
+		check_cmd "source" "DATE" "GNU date" "-t|--snap-retain|-T|--dest-snap-retain"
+	fi
+	
+	if [ $PROTOCOL_PORT = 'auto' ]; then
+		check_cmd "source" "SHUF" "shuf" "-P|--repl-port auto"
+	fi
+}
+
 
 #######################################################################################
 #
@@ -349,7 +460,7 @@ send_email_log() {
 create_fs_snap() {
 	SnapName="$SNAP_PREF$($DATE +%Y%m%d%H%M%S)"
 	log "-> $SRC_PATH@$SnapName Snapshot creation."
-	output=$( $ZFS snapshot $SRC_PATH\@$SnapName 2> $ERR_FILE )
+	output=$( $ZFS snapshot $RECURSIVE_SNAP $SRC_PATH\@$SnapName 2> $ERR_FILE )
 	log "-> $output"
 	check_for_error
 }
@@ -487,10 +598,10 @@ replicate_fs() {
 # Function build compression, transport protocol, etc pipelines
 #
 build_pipelines() {
-	case ${COMPRESSION^^} in
+	case $COMPRESSION in
 		GZIP)
 			COMPRESS_SRC_PIPE="$GZIP -$COMP_LEVEL -c -"
-			COMPRESS_DST_PIPE="$RMT_ZCAT -c "
+			COMPRESS_DST_PIPE="$RMT_GZIP -dc"
 			;;
 		XZ)
 			COMPRESS_SRC_PIPE="$XZ -$COMP_LEVEL -c -"
@@ -605,29 +716,31 @@ clean_old_snaps() {
 	fi
 
 	# check target systems' snaps and cleanup as needed
-	ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep $TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
+	if [ $REPLICATE == true ]; then
+		ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep $TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
 
-	RetainDateTime=$($DATE +%Y%m%d%H%M%S --date="$RMT_MAX_TIME")
-	while read dsnaps
-	do
-		stringpos=0
-		let stringpos=$(expr index "$dsnaps" @)+${#SNAP_PREF}
-		SnapDateTime=${dsnaps:$stringpos}
+		RetainDateTime=$($DATE +%Y%m%d%H%M%S --date="$RMT_MAX_TIME")
+		while read dsnaps
+		do
+			stringpos=0
+			let stringpos=$(expr index "$dsnaps" @)+${#SNAP_PREF}
+			SnapDateTime=${dsnaps:$stringpos}
 		
-		# skip snapshots w/ non-numeric prefixes
-		#  if no prefix then all snapshot will be returned
-		#  need to ensure $SnapDateTime is numeric for comparison to $RetainDateTime
-		if [ $REPLICATE == true ]; then
-			if [ $(echo ${SnapDateTime} | grep -c ^[0-9]) -eq 1 ] && [ ${#SnapDateTime} -eq 14 ]; then
-				if [ $RetainDateTime -gt $SnapDateTime ]; then
-					log "-> Destroying snapshot $TGT_PATH@$SNAP_PREF$SnapDateTime on $TGT_HOST"
-					log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS destroy $TGT_PATH\@$SNAP_PREF$SnapDateTime)"
+			# skip snapshots w/ non-numeric prefixes
+			#  if no prefix then all snapshot will be returned
+			#  need to ensure $SnapDateTime is numeric for comparison to $RetainDateTime
+			if [ $REPLICATE == true ]; then
+				if [ $(echo ${SnapDateTime} | grep -c ^[0-9]) -eq 1 ] && [ ${#SnapDateTime} -eq 14 ]; then
+					if [ $RetainDateTime -gt $SnapDateTime ]; then
+						log "-> Destroying snapshot $TGT_PATH@$SNAP_PREF$SnapDateTime on $TGT_HOST"
+						log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS destroy $TGT_PATH\@$SNAP_PREF$SnapDateTime)"
+					fi
 				fi
 			fi
+		done < $DSNAP_LIST
+		if [ -f $DSNAP_LIST ]; then
+			rm $DSNAP_LIST
 		fi
-	done < $DSNAP_LIST
-	if [ -f $DSNAP_LIST ]; then
-		rm $DSNAP_LIST
 	fi
 }
 
@@ -681,6 +794,10 @@ while [ $# -gt 0 ];do
              let pos=$(expr index "$SSH_TGT_HOST" @)
              TGT_HOST=${SSH_TGT_HOST:$pos}
              [ -z $TGT_HOST ] && TGT_HOST=$SSH_TGT_HOST
+             
+             ## remote host configuration (optional)
+             [ -f $CONFIG_PATH/$TGT_HOST.conf ] && . $CONFIG_PATH/$TGT_HOST.conf
+
              ;;
          -p|--port)
              shift
@@ -811,6 +928,9 @@ while [ $# -gt 0 ];do
          -6|--ip6)
          	IP_VERSION='-6'
          	;;
+     	-R|--recurse)
+     		RECURSIVE_SNAP='-r'
+     		;;
          -h|--help)
          	usage
          	;;
@@ -822,14 +942,14 @@ while [ $# -gt 0 ];do
      shift
 done
 
-## remote host configuration (optional)
-[ -f $CONFIG_PATH/$TGT_HOST.conf ] && . $CONFIG_PATH/$TGT_HOST.conf
-
 # check if we can write to log file
 if [ -n $LOG_FILE ] && [ ! -w $LOG_FILE ]; then
 	echo "ERROR: can't write to log file $LOG_FILE"
 	exit 1
 fi
+
+# check we have commands to run
+launch_check
 
 # lock & err file isolation based on source path
 src_path_hash=${SRC_PATH//\//#}
