Merge most changes from whorfin's pull request and implement most of his logic.
Signed-off-by: srlefevre <slefevre@indy.rr.com>

diff --git a/zfs-repl b/zfs-repl
--- a/zfs-repl
+++ b/zfs-repl
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
-# Date: 2013-02-23
-# Version: 2.5.12
+# Date: 2014-10-14
+# Version: 2.6.1
 #
 # Credits: 
 #    Mike La Spina for the original concept and script http://blog.laspina.ca/
@@ -9,12 +9,53 @@
 #      http://linuxzfs.blogspot.com/2012/08/zfs-replication-script.html
 #      https://github.com/kattunga/zfs-scripts.git
 #    slefevre
-#  
+#    whorfin
+#
 # Function:
 #    Provides snapshot and send process which replicates a ZFS dataset from a source to target server.
 #    Maintains a runing snapshot archive for X time
 #
 # Enhancements/Fixes:
+# 2014.10.14
+# by slefevre
+#   - Incorporate majority of whorfin's pull request changes
+#   - fix remote netcat option
+#   - Added --invert-clean option used to reverse the snapshot selection logic of --clean-snaps
+#     When used w/ --prefix & --clean-snaps it keeps all snapshots matching the prefix and deletes all other
+#     snapshots on the target system through the clean_remote_snaps function.
+#   - Added --clean-after option to run clean_remote_snaps function after replication.
+# 2014.06/23
+# by whorfin
+#   - Pipeline construction sends ALL stderr of pipeline to ERR_LOG
+#     This is good as we catch any problems including zfs send
+#     or compress/decompress/en/decrypt/socket errors, but breaks PV stats
+#     so --stats option is removed
+# 2014.06/20
+# by whorfin
+#   - All pipeline optimization collapsed; SSH not separate pipe build
+#     This means stats now work for SSH, and one could be
+#     extra paranoid and further encrypt the stream sent over SSH
+# 2014.06/19
+# by whorfin
+#   - Cleanup SSH optimization branch
+# 2014.06/18
+# by whorfin
+#   - Pipeline for non-SSH case is optimized; no more "| cat - |"
+#   - Fixes to really do the things previously promised...
+#   - TODO [?]: note that if a recursive replication fails for a
+#     sub-branch, manual intervention will be required.
+#     Delete parent snapshots on target back to the most recent snap
+#     present for all children, then run with "--no-snap"
+# 2014.06/17
+# by whorfin
+#   - Important Bugfix: lack of quotes on echo and "^$" on grep -c meant
+#     substrings could match in clean_remote_snaps
+#   - Preparing for optimized pipes; already optimize SSH
+# 2014.06/16
+# by whorfin
+#   - socat run in unidirectional mode, "STDIO" explicit
+#   - Added socat command and TCP socket argument mechanisms
+#   - Add OmniOS/SmartOS "pkgin" paths to find socat
 #  2014.06/01
 #  by  slefevre
 #    - added --no-email option to supress email of log. Overrides config file.
@@ -126,12 +167,16 @@ RMT_OPENSSL=
 SSH_CIPHER=
 PROTOCOL_PORT='auto'
 NC_OPTS=""
-RMT_NC_OPTS="-l"
+RMT_NC_OPTS=""
 OPENSSL_OPTS="enc -e -aes-128-cbc"
 RMT_OPENSSL_OPTS="enc -d -aes-128-cbc"
 SYSLOG=false
 MBUFFER_OPTS="-s 128k -m 256M -q"
 RMT_MBUFFER_OPTS="-s 128k -m 256M -q"
+SOCAT_OPTS=
+SOCAT_TCP_OPTS="retry=5"
+RMT_SOCAT_OPTS=
+RMT_SOCAT_TCP_OPTS=
 DATE_FORMAT="+%Y-%m-%d %H:%M:%S"
 REPL_INIT_TIMEOUT=120
 
@@ -158,6 +203,8 @@ RMT_MAX_TIME=
 VERBOSE=
 MOUNT=false
 CLEAN=false
+INVERT_CLEAN=false
+CLEAN_AFTER=false
 COMPARE=false
 SNAPSHOT=true
 RECURSIVE_SNAP=
@@ -239,7 +286,12 @@ usage() {
 	echo "                      descendent datasets"
 	echo "  -F --force-recv   Force receive on target dataset. See 'man zfs -F'"
 	echo "  -v --verbose      verbose"
-	echo "  -c --clean-snaps  clean snapshots in target that are not in source"
+	echo "  -c --clean-snaps  clean snapshots in target that are not in source before"
+	echo "                    replication"
+	echo "     --invert-clean reverse the --clean-snaps logic so snapshot prefix is"
+	echo "                    not deleted"
+	echo "     --clean-after  clean snapshots in target that are not in source after"
+	echo "                    replication"
 	echo "  -k --compare      compare source and target with checksum using rsync"
 	echo "  -n --no-snap      do not snapshot"
 	echo "  -r --no-repl      do not replicate"
@@ -305,7 +357,7 @@ check_cmd() {
 			[ -z "${!var_name}" ] && log_error "-> ERROR: ${exec_name} is not defined for target system. Check ${var_name}= value in /etc/$(basename $0 .sh)/${TGT_HOST}.conf. '$opt_msg' isn't available with current configuration!"
 			;;
 	esac
-#	echo "${!var_name} OK!"
+
 }
 
 #######################################################################################
@@ -372,10 +424,6 @@ launch_check() {
 		check_cmd "target" "RMT_OPENSSL" "openssl" "$option"
 	fi
 
-	if [ $STATS == true ]; then
-		check_cmd "source" "PV" "pv (pipeview)" "-S|--stats"
-	fi
-		
 	if [ $PROTOCOL_PORT = 'auto' ]; then
 		check_cmd "source" "SHUF" "shuf" "-P|--repl-port auto"
 	fi
@@ -589,15 +637,20 @@ replicate_fs() {
 	
 			#fi
 	esac
+
+	declare -a SRC_PIPELINE
+	declare -a DST_PIPELINE
 	build_pipelines
 	
 	case "$PROTOCOL" in
 		# using ssh (for remote networks)
 		SSH)
 			if [ $DEBUG = true ]; then
-				log "DEBUG: $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT \"$COMPRESS_DST_PIPE | $ZFS_RECV\""
+#				log "DEBUG: $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT \"$COMPRESS_DST_PIPE | $ZFS_RECV\""
+				log "DEBUG: $SRC_PIPELINE_CMDS | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT \"$DST_PIPELINE_CMDS\""
 			fi
-			log "-> $( $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT "$COMPRESS_DST_PIPE | $ZFS_RECV" 2> $ERR_FILE )"
+#			log "-> $( $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT "$COMPRESS_DST_PIPE | $ZFS_RECV" 2> $ERR_FILE )"
+			log "-> $( eval $SRC_PIPELINE_CMDS | ssh $IP_VERSION $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT "eval $DST_PIPELINE_CMDS" 2> $ERR_FILE )"
 			;;
 			
 		NETCAT|SOCAT|NETSOCAT|MBUFFER)
@@ -605,20 +658,24 @@ replicate_fs() {
 			# using netcat in server and socat in client, recomended, requires "netcat-traditional", must uninstall "netcat-openbds"
 
 			if [ $DEBUG = true ]; then
-				log "DEBUG: Source pipeline = $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE"
-				log "DEBUG: Destination pipeline = ssh $IP_VERSION $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT \"$PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV\""
+#				log "DEBUG: Source pipeline = $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE"
+#				log "DEBUG: Destination pipeline = ssh $IP_VERSION $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT \"$PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV\""
+				log "DEBUG: Source pipeline = $SRC_PIPELINE_CMDS"
+				log "DEBUG: Destination pipeline = ssh $IP_VERSION $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT \"$DST_PIPELINE_CMDS\""
 			fi
 			# start 'zfs send' pipeline
 			#  The timing of when to start sender differs between systems and the current load on the receiver.  This trick keeps everyone in sync.
 			#  The pipeline waits until 'zfs receive' pipeline is ready with '---' in $ERR_FILE
 		
 			replication_status init
-			(c=0;t=0; while [ $c -eq 0 ]; do sleep 1; [ -s $ERR_FILE ] && c=$(grep -c ^---$ $ERR_FILE); t=$(( t + 1 )); if [ $t -gt $REPL_INIT_TIMEOUT ]; then kill 0; exit 1; fi; done; $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE 2>> $ERR_FILE ) &
-			[ $STATS = true ] && echo "     stats  xfer'd  time    rate"
+#			(c=0;t=0; while [ $c -eq 0 ]; do sleep 1; [ -s $ERR_FILE ] && c=$(grep -c ^---$ $ERR_FILE); t=$(( t + 1 )); if [ $t -gt $REPL_INIT_TIMEOUT ]; then kill 0; exit 1; fi; done; $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE 2>> $ERR_FILE ) &
+#			[ $STATS = true ] && echo "     stats  xfer'd  time    rate"
+			(c=0;t=0; while [ $c -eq 0 ]; do sleep 1; [ -s $ERR_FILE ] && c=$(grep -c ^---$ $ERR_FILE); t=$(( t + 1 )); if [ $t -gt $REPL_INIT_TIMEOUT ]; then kill 0; exit 1; fi; done; eval $SRC_PIPELINE_CMDS 2>> $ERR_FILE ) &
 
 			# start 'zfs receive' pipeline
 			#  pipeline echos '---' to stderr (i.e. $ERR_FILE) to indicate ready to start
-			log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT "echo '---' 1>&2; $PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV" 2>> $ERR_FILE)"
+#			log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT "echo '---' 1>&2; $PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV" 2>> $ERR_FILE)"
+			log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT "echo '---' 1>&2; eval $DST_PIPELINE_CMDS" 2>> $ERR_FILE)"
 			replication_status finished
 			
 			# remove start indicator (i.e. "---") for $ERR_FILE
@@ -644,51 +701,80 @@ build_pipelines() {
 			COMPRESS_DST_PIPE="$RMT_XZCAT -c "
 			;;
 		*)
-			COMPRESS_SRC_PIPE="$CAT -"
-			COMPRESS_DST_PIPE="$RMT_CAT -"
+			unset COMPRESS_SRC_PIPE
+			unset COMPRESS_DST_PIPE
 			;;
 	esac
 
 	case $PROTOCOL in
 		NETCAT)
 			PROTOCOL_SRC_PIPE="$NC $IP_VERSION $NC_OPTS $TGT_HOST $PROTOCOL_PORT"
-			PROTOCOL_DST_PIPE="$RMT_NC $IP_VERSION $RMT_NC_OPTS $PROTOCOL_PORT"
+			PROTOCOL_DST_PIPE="$RMT_NC $IP_VERSION $RMT_NC_OPTS -l $PROTOCOL_PORT"
 			;;
 		SOCAT)
-			PROTOCOL_SRC_PIPE="$SOCAT - $IP_VERSION tcp:$TGT_HOST:$PROTOCOL_PORT,retry=5"
-			PROTOCOL_DST_PIPE="$RMT_SOCAT $IP_VERSION tcp-listen:$PROTOCOL_PORT - "
+			PROTOCOL_SRC_PIPE="$SOCAT -u $SOCAT_OPTS STDIO $IP_VERSION tcp:$TGT_HOST:$PROTOCOL_PORT,$SOCAT_TCP_OPTS"
+			PROTOCOL_DST_PIPE="$RMT_SOCAT -u $RMT_SOCAT_OPTS $IP_VERSION tcp-listen:$PROTOCOL_PORT,$RMT_SOCAT_TCP_OPTS STDIO"
 			;;
 		NETSOCAT)
-			PROTOCOL_SRC_PIPE="$SOCAT - $IP_VERSION tcp:$TGT_HOST:$PROTOCOL_PORT,retry=5"
-			PROTOCOL_DST_PIPE="$RMT_NC $IP_VERSION $RMT_NC_OPTS $PROTOCOL_PORT"
+			PROTOCOL_SRC_PIPE="$SOCAT -u $SOCAT_OPTS STDIO $IP_VERSION tcp:$TGT_HOST:$PROTOCOL_PORT,$SOCAT_TCP_OPTS"
+			PROTOCOL_DST_PIPE="$RMT_NC $IP_VERSION $RMT_NC_OPTS -l $PROTOCOL_PORT"
 			;;
 		MBUFFER)
 			PROTOCOL_SRC_PIPE="$MBUFFER $IP_VERSION $MBUFFER_OPTS -O $TGT_HOST:$PROTOCOL_PORT"
 			PROTOCOL_DST_PIPE="$RMT_MBUFFER $IP_VERSION $RMT_MBUFFER_OPTS -I $PROTOCOL_PORT"
 			;;
 		*)
-			PROTOCOL_SRC_PIPE=""
-			PROTOCOL_DST_PIPE=""
+			unset PROTOCOL_SRC_PIPE
+			unset PROTOCOL_DST_PIPE
 			;;
 	esac
 
-	if [ $STATS = true ]; then
-		if [ -z $COMPRESSION ]; then
-			STATS_SRC_PIPE="$PV -N zfs-stream"
-		else
-			STATS_SRC_PIPE="$PV -N compressed"
-		fi
-	else
-		STATS_SRC_PIPE="$CAT -"
-	fi
-	
 	if [ $ENCRYPT = true ]; then
 		ENCRYPT_SRC_PIPE="$OPENSSL $OPENSSL_OPTS -k $ENCRYPT_PASSWORD"
 		ENCRYPT_DST_PIPE="$RMT_OPENSSL $RMT_OPENSSL_OPTS -k $ENCRYPT_PASSWORD"
 	else
-		ENCRYPT_SRC_PIPE="$CAT -"
-		ENCRYPT_DST_PIPE="$RMT_CAT -"
+		unset ENCRYPT_SRC_PIPE
+		unset ENCRYPT_DST_PIPE
 	fi
+	
+	# construct the pipelines now
+	SRC_PIPELINE[0]="$ZFS_SEND"
+	if [ ! -z "$COMPRESS_SRC_PIPE" ]; then
+		SRC_PIPELINE[${#SRC_PIPELINE[@]}]="$COMPRESS_SRC_PIPE"
+	fi
+	if [ ! -z "$ENCRYPT_SRC_PIPE" ]; then
+		SRC_PIPELINE[${#SRC_PIPELINE[@]}]="$ENCRYPT_SRC_PIPE"
+	fi
+	if [ ! -z "$PROTOCOL_SRC_PIPE" ]; then
+		SRC_PIPELINE[${#SRC_PIPELINE[@]}]="$PROTOCOL_SRC_PIPE"
+	fi
+	if [ ! -z "$PROTOCOL_DST_PIPE" ]; then
+		DST_PIPELINE[${#DST_PIPELINE[@]}]="$PROTOCOL_DST_PIPE"
+	fi
+	if [ ! -z "$ENCRYPT_DST_PIPE" ]; then
+		DST_PIPELINE[${#DST_PIPELINE[@]}]="$ENCRYPT_DST_PIPE"
+	fi
+	if [ ! -z "$COMPRESS_DST_PIPE" ]; then
+		DST_PIPELINE[${#DST_PIPELINE[@]}]="$COMPRESS_DST_PIPE"
+	fi
+	DST_PIPELINE[${#DST_PIPELINE[@]}]="$ZFS_RECV"
+
+	# Build commands to eval
+	SRC_PIPELINE_CMDS="${SRC_PIPELINE[0]}"
+	pl=${#SRC_PIPELINE[@]}
+	for (( i=1; i<${pl}; i++ ));
+	do
+		SRC_PIPELINE_CMDS="${SRC_PIPELINE_CMDS} | ${SRC_PIPELINE[$i]}"
+	done
+
+	DST_PIPELINE_CMDS="${DST_PIPELINE[0]}"
+	pl=${#DST_PIPELINE[@]}
+	for (( i=1; i<${pl}; i++ ));
+	do
+		DST_PIPELINE_CMDS="${DST_PIPELINE_CMDS} | ${DST_PIPELINE[$i]}"
+	done
+
+	# pipelines built
 }
 
 #######################################################################################
@@ -696,10 +782,17 @@ build_pipelines() {
 # Function to clean up snapshots that are in target host but not in source
 #
 clean_remote_snaps() {
-	ssnap_list=$($ZFS list -H -o name -t snapshot | grep  $SRC_PATH\@${SNAP_PREF})
+	local GREP_OPT=""
 
-	ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep $TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
+	ssnap_list=$($ZFS list -H -o name -t snapshot | grep  ^$SRC_PATH\@${SNAP_PREF})
+	
+	# invert snapshot selection with 'grep -v'
+	if [ $INVERT_CLEAN == true ]; then
+		GREP_OPT="-v"
+	fi
 
+	ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep ^$TGT_PATH\@ | grep $GREP_OPT ^$TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
+	
 	while read dsnaps
 	do
 		echo "Snapshot = $dsnaps"
@@ -707,7 +800,7 @@ clean_remote_snaps() {
 		let stringpos=$(expr index "$dsnaps" @)+${#SNAP_PREF}
 		SnapName=${dsnaps:$stringpos}
 
-		if [ $(echo $ssnap_list | grep -c $SRC_PATH\@${SNAP_PREF}${SnapName}) -eq 0 ]; then
+		if [ $(echo $ssnap_list | grep -c ^$SRC_PATH\@${SNAP_PREF}${SnapName}$) -eq 0 ]; then
 			log "-> Destroying snapshot $dsnaps on $TGT_HOST"
 			log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS destroy $RECURSIVE_SNAP $dsnaps)"
 		fi
@@ -753,7 +846,7 @@ clean_old_snaps() {
 
 	# check target systems' snaps and cleanup as needed
 	if [ $REPLICATE == true ]; then
-		ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep $TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
+		ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep ^$TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
 
 		RetainDateTime=$($DATE +%Y%m%d%H%M%S --date="$RMT_MAX_TIME")
 		while read dsnaps
@@ -769,7 +862,7 @@ clean_old_snaps() {
 				if [ $(echo ${SnapDateTime} | grep -c ^[0-9]) -eq 1 ] && [ ${#SnapDateTime} -eq 14 ]; then
 					if [ $RetainDateTime -gt $SnapDateTime ]; then
 						log "-> Destroying snapshot $TGT_PATH@$SNAP_PREF$SnapDateTime on $TGT_HOST"
-						log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS destroy $TGT_PATH\@$SNAP_PREF$SnapDateTime)"
+						log "-> $(ssh $IP_VERSION -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS destroy $RECURSIVE_SNAP $TGT_PATH\@$SNAP_PREF$SnapDateTime)"
 					fi
 				fi
 			fi
@@ -931,6 +1024,12 @@ while [ $# -gt 0 ];do
          -c|--clean-snaps)
             CLEAN=true
             ;;
+          --invert-clean)
+            INVERT_CLEAN=true
+            ;;
+          --clean-after)
+            CLEAN_AFTER=true
+            ;;
          -k|--compare)
             COMPARE=true
             ;;
@@ -961,9 +1060,6 @@ while [ $# -gt 0 ];do
          	;;
          -D|--debug)
             DEBUG=true
-            ;;
-         -S|--stats)
-            STATS=true
             ;;
          -4|--ip4)
          	IP_VERSION='-4'
@@ -1081,7 +1177,7 @@ if [ $REPLICATE == true ]; then
 			log "-> Use option -z|--create-dest to create file system in target host"
 		fi
 	else
-		# Clean up any snapshots in target that is not source
+		# Clean up any snapshots in target that is not in source
 		if [ $CLEAN == true ]; then
 			clean_remote_snaps 2> $ERR_FILE
 			check_for_error
@@ -1091,6 +1187,12 @@ if [ $REPLICATE == true ]; then
 		replicate_fs repl 2> $ERR_FILE
 		check_for_error
 
+		# Clean up any snapshots in target that is not in source
+		if [ $CLEAN_AFTER == true ]; then
+			clean_remote_snaps 2> $ERR_FILE
+			check_for_error
+		fi
+		
 		# Clean up any snapshots that are old.
 		if [ "$MAX_TIME" != "" ]; then
 			clean_old_snaps 2> $ERR_FILE
