handle error in starting replication

diff --git a/zfs-repl b/zfs-repl
--- a/zfs-repl
+++ b/zfs-repl
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
-# Date: 2013-02-02
-# Version: 2.5
+# Date: 2013-02-05
+# Version: 2.5.2
 #
 # Credits: 
 #    Mike La Spina for the original concept and script http://blog.laspina.ca/
@@ -14,7 +14,13 @@
 #    Provides snapshot and send process which replicates a ZFS dataset from a source to target server.
 #    Maintains a runing snapshot archive for X time
 #
-# Enhancements:
+# Enhancements/Fixes:
+#  2014.02.07
+#   By slefevre
+#   - handle condition where 'zfs recv' doesn't start timely. (Create a initiation timeout period.)
+#  2014.02.05
+#   By slefevre
+#   - fixed timing issue where 'zfs send' thread started before 'zfs recv' thread was started
 #  2014.02.02
 #   By slefevre
 #   - added long command line options, arg checking, general clean up and polishing
@@ -94,14 +100,14 @@ RMT_OPENSSL_OPTS="enc -d -aes-128-cbc"
 SYSLOG=false
 MBUFFER_OPTS="-s 128k -m 256M -q"
 RMT_MBUFFER_OPTS="-s 128k -m 256M -q"
-PIPELINE_DELAY=5
 DATE_FORMAT="+%Y-%m-%d %H:%M:%S"
+REPL_INIT_TIMEOUT=120
 
-# process files
-#  set LOG_FILE to null to disable.  (e.g. LOG_FILE= )
+# files
+# set LOG_FILE to null to disable.  (e.g. LOG_FILE= )
 LOG_FILE=/var/log/$(basename $0 .sh).log
 #LOG_FILE=
-TMP_PATH=/tmp/$(basename $0 .sh).$RANDOM
+TMP_PATH=/tmp/$(basename $0 .sh).$$
 RSYNC_LOG=$TMP_PATH/rsync.stats
 ERR_FILE=$TMP_PATH/error
 EMAIL_LOG=$TMP_PATH/emaillog
@@ -135,6 +141,9 @@ STATS=false
 ZFS_CREATE_OPTS=
 ENCRYPT=false
 ENCRYPT_PASSWORD=
+# values: none, init, finished
+REPL_STATUS=none
+SENT_MAIL=false
 
 declare -a on_exit_items
 ####################################Function###########################################
@@ -143,10 +152,9 @@ declare -a on_exit_items
 #
 on_exit() {
 	sig="$1"; shift
-	[ $DEBUG == true ] && echo "on_exit: signal = $sig"
-	[ $sig != EXIT ] && log "Received signal $sig.  Shutting down!"
-    for i in "${on_exit_items[@]}"
-    do
+	[ $DEBUG == true ] && log "on_exit: signal = $sig"
+#	[ $sig != EXIT ] && log "Received signal $sig.  Shutting down!"
+    for i in "${on_exit_items[@]}"; do
         [ $DEBUG == true ] && log "on_exit: $i"
         eval $i
     done
@@ -177,9 +185,9 @@ on_exit_run() {
 ####################################Function###########################################
 #######################################################################################
 #
-# show_help
+# usage
 #
-show_help() {
+usage() {
 	echo "Usage: $(basename $0) "
 	echo "  -H --host         target [user@]host"
 	echo "  -p --port         target ssh port"
@@ -208,14 +216,15 @@ show_help() {
 	echo "  -C --compression  compression to use with protocol"
 	echo "      GZIP          gzip compression"
 	echo "      XZ            xz compression"
-	echo "  -P --repl-port    replication port for non-ssh protocols (default: auto)"
+	echo "      NONE          disable compression"
+	echo "  -P --repl-port    replication port (for non-ssh protocols) (default: auto)"
 	echo "  -l --comp-level   compression level 1..9 (default 6)"
 	echo "  -q --quiet        quiet. suppress output to stdout. usefull for cron jobs"
 	echo "  -m --email-errors email on errors"
 	echo "  -M --email        always email log"
 	echo "  -D --debug        show diagnositc information"
-	echo "  -S --stats        display transfer stats for non-ssh protocols"
-	echo "  -e --encrypt      encrypt zfs stream over network for non-ssh protocols"
+	echo "  -S --stats        display transfer stats (for non-ssh protocols)"
+	echo "  -e --encrypt      encrypt zfs stream over network (for non-ssh protocols)"
 	echo "  -w --pass         encryption password (default: auto generated)"
 	echo "  -h --help         display usage options "
 	exit 
@@ -230,16 +239,37 @@ generate_password() {
 	ENCRYPT_PASSWORD=${ENCRYPT_PASSWORD//$'\n'/}
 }
 
-
+#######################################################################################
+#
+# Function generate random password 
+#
+replication_status() {
+	if [ $# -eq 1 ]; then 
+		case ${1,,} in
+			none|init|finished)
+				REPL_STATUS=${1,,}
+				;;
+		esac
+	else
+		case $REPL_STATUS in
+			none|finished)
+				;;
+			init)
+				echo "ERROR: zfs replication failed." >> $ERR_FILE
+				echo "zfs receive thread may have failed to start." >> $ERR_FILE
+				cat $ERR_FILE >> $EMAIL_LOG
+				;;
+		esac
+	fi
+}
 #######################################################################################
 #
 # Function check if error was logged
 #
 check_for_error() {
-
 	if [ -s "$ERR_FILE" ]; then
-		log $(cat "$ERR_FILE")
-		[ $ERR_MAIL = true ] && send_email_log force
+		log "$(cat $ERR_FILE)"
+		send_email_log
 		exit 1
 	fi
 }
@@ -249,7 +279,7 @@ check_for_error() {
 # Function log error
 #
 log_error() {
-	echo $1 > $ERR_FILE
+	echo "$1" > $ERR_FILE
 	check_for_error
 }
 
@@ -258,10 +288,11 @@ log_error() {
 # Function log to std out and log file(s)
 #
 log() {
+	# if log has new lines, log each line separately
 	if [[ $1 == *$'\n'* ]]; then
 		local IFS=$'~'
 		for l in ${1//$'\n'/'~   '}; do
-			log $l
+			log "$l"
 		done
 		return
 	fi
@@ -270,19 +301,19 @@ log() {
 		date_line=$($DATE "$DATE_FORMAT")
 		line="$date_line $1"
 		if [ $QUIET = false ]; then
-			echo $line
+			echo "$line"
 		fi
 		if [ -n "$LOG_FILE" ]; then
-			echo $line >> "$LOG_FILE" 2> /dev/null
+			echo "$line" >> $LOG_FILE 2> /dev/null
 		fi
 		if [[ ( $SENDMAIL = true || $ERR_MAIL = true ) && -n $EMAIL_LOG ]]; then
-			echo $line >> "$EMAIL_LOG"
+			echo "$line" >> $EMAIL_LOG 2> /dev/null
 		fi
 		line="$1"
 		if [ $SYSLOG = true ]; then
 			#fix lines beginning w/ '->' as logger reads as cl option
 			if [ "->" == "${line:0:2}" ]; then
-				line=${line:2}
+				line="${line:2}"
 			fi
 			$LOGGER -t $(basename $0) "$line"
 		fi
@@ -294,16 +325,14 @@ log() {
 # Function email log file
 #
 send_email_log() {
-	flag=
-	[ $# -eq 1 ] && flag=$1
-	if [[ ( $SENDMAIL = true || $flag = force ) && -n $EMAIL_LOG && -s $EMAIL_LOG ]]; then
-		$MAILX -r "$mail_from" -s "$mail_subject" $mail_to < $EMAIL_LOG
-		[ $DEBUG = true ] && echo "Sent email to $mail_to."
-		# send email only once
-		SENDMAIL=false
-		#ERR_MAIL=false
+	if [ $SENT_MAIL = false ]; then
+		if [[ ( $SENDMAIL = true || ( $ERR_MAIL = true && -s $ERR_FILE ) ) && -n $EMAIL_LOG && -s $EMAIL_LOG ]]; then
+			$MAILX -r "$mail_from" -s "$mail_subject" $mail_to < $EMAIL_LOG
+			[ $DEBUG = true ] && echo "Sent email to $mail_to."
+			# send email only once
+			SENT_MAIL=true
+		fi
 	fi
-
 }
 
 #######################################################################################
@@ -311,7 +340,6 @@ send_email_log() {
 # Function Issue a snapshot for the source zfs path
 #
 create_fs_snap() {
-
 	SnapName="$SNAP_PREF$($DATE +%Y%m%d%H%M%S)"
 	log "-> $SRC_PATH@$SnapName Snapshot creation."
 	output=$( $ZFS snapshot $SRC_PATH\@$SnapName 2> $ERR_FILE )
@@ -325,7 +353,6 @@ create_fs_snap() {
 # variable target_fs_name.
 #
 target_fs_exists() {
-
 	target_fs_name=$(ssh -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -o name -H $TGT_PATH 2> $ERR_FILE | tail -1 )
 	if [ -s "$ERR_FILE" ]; 	then
 		path_error=$(grep "$TGT_PATH" $ERR_FILE)
@@ -336,7 +363,6 @@ target_fs_exists() {
 			log "-> $TGT_PATH file system does not exist on target host $TGT_HOST."
 		fi
 	fi
-	
 }
 
 #######################################################################################
@@ -345,14 +371,12 @@ target_fs_exists() {
 # both the source and destination hosts.
 #
 check_last_source_snap() {
-
 	last_snap_source=$( $ZFS list -o name -t snapshot -H 2> $ERR_FILE | grep $SRC_PATH\@ | tail -1 )
 	check_for_error
 	if [ "$last_snap_source" == "" ]
 	then
 		log_error "There is no snapshots in source filesystem $SRC_PATH"
 	fi
-
 }
 
 #######################################################################################
@@ -361,7 +385,6 @@ check_last_source_snap() {
 # both the source and destination hosts.
 #
 check_last_target_snap() {
-
 	last_snap_target=$( ssh -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -r -t snapshot 2> $ERR_FILE | grep $TGT_PATH\@ | tail -1 )
 	check_for_error
 	if [ "$last_snap_target" == "" ]
@@ -415,27 +438,36 @@ replicate_fs() {
 	
 	case "$PROTOCOL" in
 		# using ssh (for remote networks)
-		ssh|SSH)
+		SSH)
 			if [ $DEBUG = true ]; then
 				log "DEBUG: $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT \"$COMPRESS_DST_PIPE | $ZFS_RECV\""
 			fi
 			log "-> $( $ZFS_SEND | $COMPRESS_SRC_PIPE | ssh $SSH_CIPHER $SSH_TGT_HOST $SSH_TGT_PORT "$COMPRESS_DST_PIPE | $ZFS_RECV" 2> $ERR_FILE )"
 			;;
 			
-		netcat|NETCAT|socat|SOCAT|netsocat|NETSOCAT|mbuffer|MBUFFER)
+		NETCAT|SOCAT|NETSOCAT|MBUFFER)
 			# using netcat (local network) requires "netcat-traditional", must uninstall "netcat-openbds"
 			# using netcat in server and socat in client, recomended, requires "netcat-traditional", must uninstall "netcat-openbds"
 
 			if [ $DEBUG = true ]; then
 				log "DEBUG: Source pipeline = $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE"
-				log "DEBUG: Destination pipeline = ssh -f -n $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT \"$PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV\""
+				log "DEBUG: Destination pipeline = ssh $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT \"$PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV\""
 			fi
 			# start 'zfs send' pipeline
-			(sleep $PIPELINE_DELAY; $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE) &
-			[ $STATS = true ] && echo "     stats  xfer'd  time    bandwidth"
+			#  The timing of when to start sender differs between systems and the current load on the receiver.  This trick keeps everyone in sync.
+			#  The pipeline waits until 'zfs receive' pipeline is ready with '---' in $ERR_FILE
+		
+			replication_status init
+			(c=0;t=0; while [ $c -eq 0 ]; do sleep 1; [ -s $ERR_FILE ] && c=$(grep -c ^---$ $ERR_FILE); t=$(( t + 1 )); if [ $t -gt $REPL_INIT_TIMEOUT ]; then kill 0; exit 1; fi; done; $ZFS_SEND | $COMPRESS_SRC_PIPE | $STATS_SRC_PIPE | $ENCRYPT_SRC_PIPE | $PROTOCOL_SRC_PIPE 2> $ERR_FILE ) &
+			[ $STATS = true ] && echo "     stats  xfer'd  time    rate"
 
-			#start 'zfs receive' pipeline
-			log "-> $(ssh $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT "$PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV" 2> $ERR_FILE)"
+			# start 'zfs receive' pipeline
+			#  pipeline echos '---' to stderr (i.e. $ERR_FILE) to indicate ready to start
+			log "-> $(ssh $SSH_TGT_HOST $SSH_CIPHER $SSH_TGT_PORT "echo '---' 1>&2; $PROTOCOL_DST_PIPE | $ENCRYPT_DST_PIPE | $COMPRESS_DST_PIPE | $ZFS_RECV" 2> $ERR_FILE)"
+			replication_status finished
+			
+			# remove start indicator (i.e. "---") for $ERR_FILE
+			sed -i '/^---$/d' $ERR_FILE
 			;;
 	esac
 
@@ -447,12 +479,12 @@ replicate_fs() {
 # Function build compression, transport protocol, etc pipelines
 #
 build_pipelines() {
-	case $COMPRESSION in
-		gzip|GZIP)
+	case ${COMPRESSION^^} in
+		GZIP)
 			COMPRESS_SRC_PIPE="$GZIP -$COMP_LEVEL -c -"
 			COMPRESS_DST_PIPE="$RMT_ZCAT -c "
 			;;
-		xz|XZ)
+		XZ)
 			COMPRESS_SRC_PIPE="$XZ -$COMP_LEVEL -c -"
 			COMPRESS_DST_PIPE="$RMT_XZCAT -c "
 			;;
@@ -463,19 +495,19 @@ build_pipelines() {
 	esac
 
 	case $PROTOCOL in
-		netcat|NETCAT)
+		NETCAT)
 			PROTOCOL_SRC_PIPE="$NC $NC_OPTS $TGT_HOST $PROTOCOL_PORT"
 			PROTOCOL_DST_PIPE="$RMT_NC $RMT_NC_OPTS -p $PROTOCOL_PORT"
 			;;
-		socat|SOCAT)
+		SOCAT)
 			PROTOCOL_SRC_PIPE="$SOCAT - tcp4:$TGT_HOST:$PROTOCOL_PORT,retry=5"
 			PROTOCOL_DST_PIPE="$RMT_SOCAT tcp4-listen:$PROTOCOL_PORT - "
 			;;
-		netsocat|NETSOCAT)
+		NETSOCAT)
 			PROTOCOL_SRC_PIPE="$SOCAT - tcp4:$TGT_HOST:$PROTOCOL_PORT,retry=5"
 			PROTOCOL_DST_PIPE="$RMT_NC $RMT_NC_OPTS -p $PROTOCOL_PORT"
 			;;
-		mbuffer|MBUFFER)
+		MBUFFER)
 			PROTOCOL_SRC_PIPE="$MBUFFER $MBUFFER_OPTS -O $TGT_HOST:$PROTOCOL_PORT"
 			PROTOCOL_DST_PIPE="$RMT_MBUFFER $RMT_MBUFFER_OPTS -I $PROTOCOL_PORT"
 			;;
@@ -509,7 +541,6 @@ build_pipelines() {
 # Function to clean up snapshots that are in target host but not in source
 #
 clean_remote_snaps() {
-
 	ssnap_list=$($ZFS list -H -o name -t snapshot | grep  $SRC_PATH\@${SNAP_PREF})
 
 	ssh -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS list -H -o name -t snapshot | grep $TGT_PATH\@${SNAP_PREF} > $DSNAP_LIST
@@ -540,7 +571,6 @@ clean_remote_snaps() {
 # the last snapshot should not be deleted, at least one snapshot must be keeped
 #
 clean_old_snaps() {
-
 	check_last_source_snap  
 
 	$ZFS list -o name -t snapshot | grep  $SRC_PATH\@$SNAP_PREF > $SNAP_LIST
@@ -598,7 +628,6 @@ clean_old_snaps() {
 # Function to compare filesystems with checksum
 #
 compare_filesystems() {
-
 	check_last_source_snap
 	stringpos=0
 	let stringpos=$(expr index "$last_snap_source" @)
@@ -608,7 +637,6 @@ compare_filesystems() {
 	stringpos=0
 	let stringpos=$(expr index "$last_snap_target" @)
 	target_snap_path=$(ssh -n $SSH_TGT_HOST $SSH_TGT_PORT $RMT_ZFS get -H -o value mountpoint $TGT_PATH)/.zfs/snapshot/${last_snap_target:$stringpos}
-
 
 	log "-> comparing $source_snap_path to $TGT_HOST:$target_snap_path"
 	if [ -f $RSYNC_LOG ]; then
@@ -635,7 +663,7 @@ compare_filesystems() {
 ## local configuration
 [ -f $CONFIG_PATH/$(basename $0).conf ] && . $CONFIG_PATH/$(basename $0).conf
 
-[ $# -eq 0 ] && show_help
+[ $# -eq 0 ] && usage
 
 while [ $# -gt 0 ];do
      case "$1" in
@@ -649,9 +677,9 @@ while [ $# -gt 0 ];do
          -p|--port)
              shift
              SSH_TGT_PORT="-p$1"
-             if [[ $SSH_TGT_PORT != *[^0-9]* ]]; then
+             if [[ $SSH_TGT_PORT != ^[0-9]+$ ]]; then
              	echo "Incorrect value $1. -p|--port must be numeric"
-             	exit 1
+             	usage
              fi
              ;;
          -s|--source)
@@ -676,13 +704,13 @@ while [ $# -gt 0 ];do
              ;;
          -o|--protocol)
              shift
-           	 case $1 in
-         	 	ssh|SSH|netcat|NETCAT|socat|SOCAT|netsocat|NETSOCAT|mbuffer|MBUFFER)
-         	 		PROTOCOL=$1
+           	 case ${1^^} in
+         	 	SSH|NETCAT|SOCAT|NETSOCAT|MBUFFER)
+         	 		PROTOCOL=${1^^}
          	 		;;
          	 	*)
          	 		echo "Incorrect protocol value $PROTOCOL. Valid -o|--protocol values: SSH NETCAT SOCAT NETSOCAT MBUFFER"
-         	 		exit 1 
+         	 		usage
          	 		;;
  	 		 esac
              ;;
@@ -692,7 +720,7 @@ while [ $# -gt 0 ];do
              	PROTOCOL_PORT=$1
          	else
              	echo "Incorrect port value $1. -P|--repl-port must be numeric or 'auto'"
-             	exit 1
+             	usage
              fi
              
              ;;
@@ -702,18 +730,21 @@ while [ $# -gt 0 ];do
              	COMP_LEVEL=$1
              else
              	echo "Incorrect compression level $1. -l|--comp-level must be numeric (1-9)"
-             	exit 1
+             	usage
              fi
              ;;
          -C|--compression)
          	 shift
-         	 case $1 in
-         	 	gzip|GZIP|xz|XZ)
-         	 		COMPRESSION=$1
+         	 case ${1^^} in
+         	 	GZIP|XZ)
+         	 		COMPRESSION=${1^^}
          	 		;;
+     	 		NONE)
+     	 			COMPRESSION=
+     	 			;;
          	 	*)
-         	 		echo "Incorrect compression value $COMPRESSION. Valid -C|--compression values: GZIP XZ"
-         	 		exit 1 
+         	 		echo "Incorrect compression value $COMPRESSION. Valid -C|--compression values: GZIP XZ NONE"
+         	 		usage
          	 		;;
  	 		 esac
          	 ;;
@@ -723,7 +754,7 @@ while [ $# -gt 0 ];do
          		ZFS_CREATE_OPTS="$ZFS_CREATE_OPTS -o $1"
          	else
          		echo "Incorrect zfs create property $1. Please see 'man zfs' for details and syntax."
-         		exit 1
+         		usage
          	fi
              ;;
          -e|--encrypt)
@@ -767,11 +798,11 @@ while [ $# -gt 0 ];do
             STATS=true
             ;;
          -h|--help)
-         	show_help
+         	usage
          	;;
          *)
          	echo "Invalid option $1."
-            show_help
+            usage
             ;;
      esac
      shift
@@ -779,6 +810,12 @@ done
 
 ## remote host configuration (optional)
 [ -f $CONFIG_PATH/$TGT_HOST.conf ] && . $CONFIG_PATH/$TGT_HOST.conf
+
+# check if we can write to log file
+if [ -n $LOG_FILE ] && [ ! -w $LOG_FILE ]; then
+	echo "ERROR: can't write to log file $LOG_FILE"
+	exit 1
+fi
 
 # lock & err file isolation based on source path
 src_path_hash=${SRC_PATH//\//#}
@@ -791,26 +828,27 @@ mkdir -p $TMP_PATH > /dev/null 2>&1
 [ $DEBUG = true ] && log "TMP_PATH = $TMP_PATH"
 
 #register exit/clean up tasks
+on_exit_run replication_status
 on_exit_run	log "End ------------------------------------------------------------"
 on_exit_run send_email_log
-[ $DEBUG = false ] && on_exit_run rm -rf $TMP_PATH
+#[ $DEBUG = false ] && on_exit_run rm -rf $TMP_PATH
 
 # check and complete parameters
-if [ "$SRC_PATH" == "" ]; then
+if [ -z $SRC_PATH ]; then
 	echo "Missing parameter source path -s|--source"
-	show_help
+	usage
 fi
 if [[ ($REPLICATE == true) || ($COMPARE == true) ]]; then
-	if [ "$TGT_HOST" == "" ]; 	then
+	if [ -z $TGT_HOST ]; 	then
 		echo "Missing parameter target host -H|--host"
-		show_help
+		usage
 	fi
-	if [ "$TGT_PATH" == "" ]; 	then
+	if [ -z $TGT_PATH ]; 	then
 		TGT_PATH=$SRC_PATH
 	fi
 	if [ -z $PROTOCOL ]; then
 		echo "Transport protocol must be specified. See -o|--protocol options."
-		show_help
+		usage
 	fi
 	# pick a port to use
 	if [ $PROTOCOL_PORT = auto ]; then
@@ -822,22 +860,23 @@ if [[ ($REPLICATE == true) || ($COMPARE == true) ]]; then
 	fi
 	# -T option not specified use -t option value
 	if [ -z "$RMT_MAX_TIME" ]; then
-		RMT_MAX_TIME=$MAX_TIME
+		RMT_MAX_TIME="$MAX_TIME"
 	fi
 fi
 
-# Check if no current replication is running
+# Check if replication is running
 if [ -e "$LOCK_FILE" ]; then
 	log_error "-> ERROR: replication is currently running."
 	exit
 fi
 
-# set the lock flag
+# set the lock flag w/ pid
 touch $LOCK_FILE > /dev/null 2>&1
 if [ $? -gt 0 ]; then
-	log_error "-> ERROR: unable to create lock file: $LOCK_FILE"
+	echo "ERROR: unable to create lock file: $LOCK_FILE"
 	exit 1
 fi
+echo $$ > $LOCK_FILE
 
 #register exit/clean up tasks
 on_exit_run rm -f $LOCK_FILE
@@ -879,7 +918,7 @@ if [ $REPLICATE == true ]; then
 	fi
 else
 	# Clean up any snapshots that are old.
-	if [ "$MAX_TIME" != "" ]; then
+	if [ -n $MAX_TIME ]; then
 		clean_old_snaps 2> $ERR_FILE
 		check_for_error
 	fi
